version: '3'
services:
  faveo-apache:
    image: tamilselvanlws/faveo-apache-php8.2:v1
    container_name: ${DOMAINNAME}-apache
    networks:
      faveo-network:
        ipv4_address: 172.24.2.11
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./${HOST_ROOT_DIR}:/var/www/html/
      - ${CUR_DIR}/certbot/letsencrypt/etc/letsencrypt/live/${DOMAINNAME}/cert.pem:/var/imported/ssl/cert.pem
      - ${CUR_DIR}/certbot/letsencrypt/etc/letsencrypt/live/${DOMAINNAME}/privkey.pem:/var/imported/ssl/privkey.pem
      - ${CUR_DIR}/certbot/letsencrypt/etc/letsencrypt/live/${DOMAINNAME}/fullchain.pem:/var/imported/ssl/fullchain.pem
    restart: always
    
  faveo-mariadb:
    image: mariadb:10.6
    container_name: ${DOMAINNAME}-mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      faveo-network:
        ipv4_address: 172.24.2.12
    restart: on-failure

  faveo-redis:
    image: redis
    container_name: ${DOMAINNAME}-redis
    ports:
      - "6379:6379"
    networks:
      faveo-network:
        ipv4_address: 172.24.2.13
    restart: always

  faveo-supervisor:
    image: tamilselvanlws/faveo-supervisor-php8.2:v1
    container_name: ${DOMAINNAME}-supervisor
    volumes:
      - ./conf/supervisor/faveo-worker.conf:/etc/supervisor/conf.d/faveo-worker.conf
      - ./${HOST_ROOT_DIR}/:/var/www/html/
    ports:
        - "9001:9001"
    depends_on:
      - faveo-apache
      - faveo-mariadb
      - faveo-redis
      - faveo-meilisearch
      - faveo-memcached
    networks:
      faveo-network:
        ipv4_address: 172.24.2.14
    restart: on-failure

  faveo-meilisearch:
    image: getmeili/meilisearch:latest
    container_name: ${DOMAINNAME}-meilisearch
    volumes:
      - ./meilisearch:/meili_data
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MASTER_KEY}
    networks:
      faveo-network:
        ipv4_address: 172.24.2.15
    restart: always

  faveo-memcached:
    image: memcached:latest
    container_name: ${DOMAINNAME}-memcached
    ports:
      - "11211:11211"
    networks:
      faveo-network:
        ipv4_address: 172.24.2.16
    restart: always

volumes:
  db-volume:
    external: 
      name: ${DOMAINNAME}-faveoDB
  
networks:
    faveo-network:
      external:
        name: ${DOMAINNAME}-faveo