docRoot                   /var/www/html/public
vhDomain                  example.com
vhAliases                 www.example.com
enableGzip                1
enableBr                  1
enableIpGeo               1

index  {
  useServer               0
  indexFiles              index.php, index.html
  autoIndex               0
}

scripthandler  {
  add                     lsapi:lsphp82 php82
}

context / {
  allowBrowse             1
  extraHeaders            <<<END_extraHeaders
Content-Security-Policy "frame-ancestors 'self'"
Referrer-Policy "no-referrer-when-downgrade"
X-Content-Type-Options "nosniff"
X-Frame-Options "SAMEORIGIN"
X-XSS-Protection "1; mode=block"
Permissions-Policy "geolocation=(self), microphone=()"
Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
Expect-CT "max-age=86400, enforce"
  END_extraHeaders


  addDefaultCharset       off
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
}

vhssl  {
  keyFile                 /var/imported/ssl/privkey.pem
  certFile                /var/imported/ssl/fullchain.pem
  certChain               1
  enableSpdy              12
  enableQuic              1
}